version: '3.8'

services:
  php:
    build:
      context: .          
      dockerfile: docker/php/Dockerfile
    container_name: php_pgsql_app
    volumes:
      - ./src:/var/www/public 
    networks:
      - app-network      
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_app
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php               
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 
